config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'question/index'
  resources :cars
  resources :supplies
  devise_for :users
get '/query/' => 'supplies#query', as: 'query'
  	 devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
   #root 'supplies#index'
  	root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <% if user_signed_in? %>


<div class="home">
<%= link_to "Cadastre seu Carro!", new_car_path,  class: "btn btn-success" ,:style=> 'color: black;'  %>
<%= link_to "Meus Carros!", cars_path,  class: "btn btn-info" ,:style=> 'color: black;'  %>
<%= link_to "Cadastre seu abastecimento!", new_supply_path,  class: "btn btn-success" ,:style=> 'color: black;'  %>
<%= link_to "Meus abastecimento!",supplies_path,  class: "btn btn-info" ,:style=> 'color: black;'  %>
<div>

  <% else %>
<div class="w3-content" style="max-width:400px">
  <div class="mySlides w3-container w3-red" >
    <h1 ><b >Afinal que posto usar? </b></h1>
    <h2><i>Entre em nosso sistema e lhe diremos, clique no botão abaixo</i></h2>
 <%= link_to "Cadastre-se", new_user_registration_path,  class: "btn btn-default" ,:style=> 'color: black;'  %>
  </div>
  <div class="mySlides w3-container w3-blue">
      <h2>Seu posto é esse ?</h2>
  </div>


</div>

<script>
var slideIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > x.length) {slideIndex = 1}
    x[slideIndex-1].style.display = "block";
    setTimeout(carousel, 2000);
}
</script>
  <%end %>