config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'question/index'
  resources :cars
  resources :supplies
  devise_for :users
get '/query/' => 'supplies#query', as: 'query'
  	 devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
   #root 'supplies#index'
  	root 'home#index'
end

app/models/supply.rb
class Supply < ApplicationRecord

	belongs_to :user
	belongs_to :car
end

app/controllers/supplies_controller.rb
  class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:show, :edit, :update, :destroy]


  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

def query
  @supplies = Supply.all
end
  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)
     @supply.user_id = current_user.id

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      form at.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.require(:supply).permit(:date, :gasStation,:car_id, :km, :liter, :fuel, :price)
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_for @supply, :html => { :class => "form-horizontal supply" } do |f| %>

  <% if @supply.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @supply.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date) %>
  </div>
  <div class="form-group">
    <%= f.label :gasStation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gasStation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gasStation) %>
  </div>
  <div class="form-group">
    <%= f.label :km, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :km, :class => 'form-control' %>
    </div>
    <%=f.error_span(:km) %>
  </div>
  <div class="form-group">
    <%= f.label :liter, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :liter, :class => 'form-control' %>
    </div>
    <%=f.error_span(:liter) %>
  </div>
  <div class="form-group">
    <%= f.label :fuel, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fuel, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fuel) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
     <%= f.label :car, :class => 'control-label col-lg-2' %>
     <div class="col-lg-10">
       <%= f.collection_select(:car_id, Car.where("user_id = ?", current_user.id),
                                           :id, :plate, :prompt => true) %>
     </div>
     <%=f.error_span(:car_id) %>
 </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                supplies_path, :class => 'btn btn-danger' %>
    </div>
  </div>

<% end %>

app/views/supplies/edit.html.erb
<%- model_class = Supply -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/supplies/index.html.erb
<%- model_class = Supply -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:gasStation) %></th>
      <th><%= model_class.human_attribute_name(:km) %></th>
      <th><%= model_class.human_attribute_name(:liter) %></th>
      <th><%= model_class.human_attribute_name(:fuel) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:car_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @supplies.each do |supply| %>
      <tr>
        <td><%= link_to supply.id, supply_path(supply) %></td>
        <td><%= supply.date %></td>
        <td><%= supply.gasStation %></td>
        <td><%= supply.km %></td>
        <td><%= supply.liter %></td>
        <td><%= supply.fuel %></td>
        <td><%= supply.price %></td>
        <td><%= supply.owner %></td>
        <td><%= supply.user_id %></td>
        <td><%= supply.car_id %></td>
        <td><%=l supply.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      supply_path(supply), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_supply_path(supply), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      supply_path(supply),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_supply_path,
            :class => 'btn btn-success' %>
            <%= link_to "Por rentabilidade e Consumo!", query_path,  class: "btn btn-success" ,:style=> 'color: black;'  %>

app/views/supplies/new.html.erb
<%- model_class = Supply -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/supplies/query.html.erb
<%- model_class = Supply -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:gasStation) %></th>
      <th>Média de Consumo</th>
      <th>Rentabilidade</th>

    </tr>
  </thead>
  <tbody>
    <% @supplies.each do |supply| %>
      <tr>

        <td><%= supply.date %></td>
        <td><%= supply.gasStation %></td>
        <td><%= format("%.2f",supply.km/supply.liter)%></td>
        <td><%= supply.km/supply.price%></td>








      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Abastecimentos", supplies_path,  class: "btn btn-success" ,:style=> 'color: black;'  %>

app/views/supplies/show.html.erb
<%- model_class = Supply -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @supply.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gasStation) %>:</strong></dt>
  <dd><%= @supply.gasStation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:km) %>:</strong></dt>
  <dd><%= @supply.km %></dd>
  <dt><strong><%= model_class.human_attribute_name(:liter) %>:</strong></dt>
  <dd><%= @supply.liter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fuel) %>:</strong></dt>
  <dd><%= @supply.fuel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @supply.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner) %>:</strong></dt>
  <dd><%= @supply.owner %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @supply.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:car_id) %>:</strong></dt>
  <dd><%= @supply.car_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              supplies_path, :class => 'btn btn-primary'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_supply_path(@supply), :class => 'btn btn-warning' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              supply_path(@supply),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>