config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'question/index'
  resources :cars
  resources :supplies
  devise_for :users
get '/query/' => 'supplies#query', as: 'query'
  	 devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: 'home#index'
   #root 'supplies#index'
  	root 'home#index'
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user
	has_many :supplies
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
     @car.user_id = current_user.id
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|

      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:plate, :model, :year)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car, :html => { :class => "form-horizontal car" } do |f| %>

  <% if @car.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :plate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :plate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:plate) %>
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :model, :class => 'form-control' %>
    </div>
    <%=f.error_span(:model) %>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
    <%=f.error_span(:year) %>
  </div>
  
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cars_path, :class => 'btn btn-primary ' %>
    </div>
  </div>

<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:plate) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.plate %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.user_id %></td>
        <td><%=l car.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      car_path(car), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_car_path,
            :class => 'btn btn-success' %>

app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:plate) %>:</strong></dt>
  <dd><%= @car.plate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @car.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @car.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @car.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              cars_path, :class => 'btn btn-primary'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_car_path(@car), :class => 'btn btn-warning' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              car_path(@car),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>